name: Déploiement optimisé

on: [push]  # Déclenché à chaque push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    
    steps:
      - uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Changer selon votre besoin

      - name: Installer les dépendances
        run: npm ci

      - name: Build
        run: npm run build
